/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as DocsQuickStartRouteImport } from './routes/docs.quick-start'
import { Route as DocsInstallationRouteImport } from './routes/docs.installation'
import { Route as DocsVelocityRefinementRouteImport } from './routes/docs.velocity.refinement'
import { Route as DocsVelocityOverviewRouteImport } from './routes/docs.velocity.overview'
import { Route as DocsVelocityKuSearchRouteImport } from './routes/docs.velocity.ku-search'
import { Route as DocsVelocityFSweepRouteImport } from './routes/docs.velocity.f-sweep'
import { Route as DocsVelocityDisruptionRouteImport } from './routes/docs.velocity.disruption'
import { Route as DocsVelocityConfigRouteImport } from './routes/docs.velocity.config'
import { Route as DocsConceptsTuningModesRouteImport } from './routes/docs.concepts.tuning-modes'
import { Route as DocsConceptsScoringRouteImport } from './routes/docs.concepts.scoring'
import { Route as DocsConceptsPidfTermsRouteImport } from './routes/docs.concepts.pidf-terms'

const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsQuickStartRoute = DocsQuickStartRouteImport.update({
  id: '/quick-start',
  path: '/quick-start',
  getParentRoute: () => DocsRoute,
} as any)
const DocsInstallationRoute = DocsInstallationRouteImport.update({
  id: '/installation',
  path: '/installation',
  getParentRoute: () => DocsRoute,
} as any)
const DocsVelocityRefinementRoute = DocsVelocityRefinementRouteImport.update({
  id: '/velocity/refinement',
  path: '/velocity/refinement',
  getParentRoute: () => DocsRoute,
} as any)
const DocsVelocityOverviewRoute = DocsVelocityOverviewRouteImport.update({
  id: '/velocity/overview',
  path: '/velocity/overview',
  getParentRoute: () => DocsRoute,
} as any)
const DocsVelocityKuSearchRoute = DocsVelocityKuSearchRouteImport.update({
  id: '/velocity/ku-search',
  path: '/velocity/ku-search',
  getParentRoute: () => DocsRoute,
} as any)
const DocsVelocityFSweepRoute = DocsVelocityFSweepRouteImport.update({
  id: '/velocity/f-sweep',
  path: '/velocity/f-sweep',
  getParentRoute: () => DocsRoute,
} as any)
const DocsVelocityDisruptionRoute = DocsVelocityDisruptionRouteImport.update({
  id: '/velocity/disruption',
  path: '/velocity/disruption',
  getParentRoute: () => DocsRoute,
} as any)
const DocsVelocityConfigRoute = DocsVelocityConfigRouteImport.update({
  id: '/velocity/config',
  path: '/velocity/config',
  getParentRoute: () => DocsRoute,
} as any)
const DocsConceptsTuningModesRoute = DocsConceptsTuningModesRouteImport.update({
  id: '/concepts/tuning-modes',
  path: '/concepts/tuning-modes',
  getParentRoute: () => DocsRoute,
} as any)
const DocsConceptsScoringRoute = DocsConceptsScoringRouteImport.update({
  id: '/concepts/scoring',
  path: '/concepts/scoring',
  getParentRoute: () => DocsRoute,
} as any)
const DocsConceptsPidfTermsRoute = DocsConceptsPidfTermsRouteImport.update({
  id: '/concepts/pidf-terms',
  path: '/concepts/pidf-terms',
  getParentRoute: () => DocsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/docs/installation': typeof DocsInstallationRoute
  '/docs/quick-start': typeof DocsQuickStartRoute
  '/docs/': typeof DocsIndexRoute
  '/docs/concepts/pidf-terms': typeof DocsConceptsPidfTermsRoute
  '/docs/concepts/scoring': typeof DocsConceptsScoringRoute
  '/docs/concepts/tuning-modes': typeof DocsConceptsTuningModesRoute
  '/docs/velocity/config': typeof DocsVelocityConfigRoute
  '/docs/velocity/disruption': typeof DocsVelocityDisruptionRoute
  '/docs/velocity/f-sweep': typeof DocsVelocityFSweepRoute
  '/docs/velocity/ku-search': typeof DocsVelocityKuSearchRoute
  '/docs/velocity/overview': typeof DocsVelocityOverviewRoute
  '/docs/velocity/refinement': typeof DocsVelocityRefinementRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs/installation': typeof DocsInstallationRoute
  '/docs/quick-start': typeof DocsQuickStartRoute
  '/docs': typeof DocsIndexRoute
  '/docs/concepts/pidf-terms': typeof DocsConceptsPidfTermsRoute
  '/docs/concepts/scoring': typeof DocsConceptsScoringRoute
  '/docs/concepts/tuning-modes': typeof DocsConceptsTuningModesRoute
  '/docs/velocity/config': typeof DocsVelocityConfigRoute
  '/docs/velocity/disruption': typeof DocsVelocityDisruptionRoute
  '/docs/velocity/f-sweep': typeof DocsVelocityFSweepRoute
  '/docs/velocity/ku-search': typeof DocsVelocityKuSearchRoute
  '/docs/velocity/overview': typeof DocsVelocityOverviewRoute
  '/docs/velocity/refinement': typeof DocsVelocityRefinementRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/docs/installation': typeof DocsInstallationRoute
  '/docs/quick-start': typeof DocsQuickStartRoute
  '/docs/': typeof DocsIndexRoute
  '/docs/concepts/pidf-terms': typeof DocsConceptsPidfTermsRoute
  '/docs/concepts/scoring': typeof DocsConceptsScoringRoute
  '/docs/concepts/tuning-modes': typeof DocsConceptsTuningModesRoute
  '/docs/velocity/config': typeof DocsVelocityConfigRoute
  '/docs/velocity/disruption': typeof DocsVelocityDisruptionRoute
  '/docs/velocity/f-sweep': typeof DocsVelocityFSweepRoute
  '/docs/velocity/ku-search': typeof DocsVelocityKuSearchRoute
  '/docs/velocity/overview': typeof DocsVelocityOverviewRoute
  '/docs/velocity/refinement': typeof DocsVelocityRefinementRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/docs/installation'
    | '/docs/quick-start'
    | '/docs/'
    | '/docs/concepts/pidf-terms'
    | '/docs/concepts/scoring'
    | '/docs/concepts/tuning-modes'
    | '/docs/velocity/config'
    | '/docs/velocity/disruption'
    | '/docs/velocity/f-sweep'
    | '/docs/velocity/ku-search'
    | '/docs/velocity/overview'
    | '/docs/velocity/refinement'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs/installation'
    | '/docs/quick-start'
    | '/docs'
    | '/docs/concepts/pidf-terms'
    | '/docs/concepts/scoring'
    | '/docs/concepts/tuning-modes'
    | '/docs/velocity/config'
    | '/docs/velocity/disruption'
    | '/docs/velocity/f-sweep'
    | '/docs/velocity/ku-search'
    | '/docs/velocity/overview'
    | '/docs/velocity/refinement'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/docs/installation'
    | '/docs/quick-start'
    | '/docs/'
    | '/docs/concepts/pidf-terms'
    | '/docs/concepts/scoring'
    | '/docs/concepts/tuning-modes'
    | '/docs/velocity/config'
    | '/docs/velocity/disruption'
    | '/docs/velocity/f-sweep'
    | '/docs/velocity/ku-search'
    | '/docs/velocity/overview'
    | '/docs/velocity/refinement'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRoute: typeof DocsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/quick-start': {
      id: '/docs/quick-start'
      path: '/quick-start'
      fullPath: '/docs/quick-start'
      preLoaderRoute: typeof DocsQuickStartRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/installation': {
      id: '/docs/installation'
      path: '/installation'
      fullPath: '/docs/installation'
      preLoaderRoute: typeof DocsInstallationRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/velocity/refinement': {
      id: '/docs/velocity/refinement'
      path: '/velocity/refinement'
      fullPath: '/docs/velocity/refinement'
      preLoaderRoute: typeof DocsVelocityRefinementRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/velocity/overview': {
      id: '/docs/velocity/overview'
      path: '/velocity/overview'
      fullPath: '/docs/velocity/overview'
      preLoaderRoute: typeof DocsVelocityOverviewRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/velocity/ku-search': {
      id: '/docs/velocity/ku-search'
      path: '/velocity/ku-search'
      fullPath: '/docs/velocity/ku-search'
      preLoaderRoute: typeof DocsVelocityKuSearchRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/velocity/f-sweep': {
      id: '/docs/velocity/f-sweep'
      path: '/velocity/f-sweep'
      fullPath: '/docs/velocity/f-sweep'
      preLoaderRoute: typeof DocsVelocityFSweepRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/velocity/disruption': {
      id: '/docs/velocity/disruption'
      path: '/velocity/disruption'
      fullPath: '/docs/velocity/disruption'
      preLoaderRoute: typeof DocsVelocityDisruptionRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/velocity/config': {
      id: '/docs/velocity/config'
      path: '/velocity/config'
      fullPath: '/docs/velocity/config'
      preLoaderRoute: typeof DocsVelocityConfigRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/concepts/tuning-modes': {
      id: '/docs/concepts/tuning-modes'
      path: '/concepts/tuning-modes'
      fullPath: '/docs/concepts/tuning-modes'
      preLoaderRoute: typeof DocsConceptsTuningModesRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/concepts/scoring': {
      id: '/docs/concepts/scoring'
      path: '/concepts/scoring'
      fullPath: '/docs/concepts/scoring'
      preLoaderRoute: typeof DocsConceptsScoringRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/concepts/pidf-terms': {
      id: '/docs/concepts/pidf-terms'
      path: '/concepts/pidf-terms'
      fullPath: '/docs/concepts/pidf-terms'
      preLoaderRoute: typeof DocsConceptsPidfTermsRouteImport
      parentRoute: typeof DocsRoute
    }
  }
}

interface DocsRouteChildren {
  DocsInstallationRoute: typeof DocsInstallationRoute
  DocsQuickStartRoute: typeof DocsQuickStartRoute
  DocsIndexRoute: typeof DocsIndexRoute
  DocsConceptsPidfTermsRoute: typeof DocsConceptsPidfTermsRoute
  DocsConceptsScoringRoute: typeof DocsConceptsScoringRoute
  DocsConceptsTuningModesRoute: typeof DocsConceptsTuningModesRoute
  DocsVelocityConfigRoute: typeof DocsVelocityConfigRoute
  DocsVelocityDisruptionRoute: typeof DocsVelocityDisruptionRoute
  DocsVelocityFSweepRoute: typeof DocsVelocityFSweepRoute
  DocsVelocityKuSearchRoute: typeof DocsVelocityKuSearchRoute
  DocsVelocityOverviewRoute: typeof DocsVelocityOverviewRoute
  DocsVelocityRefinementRoute: typeof DocsVelocityRefinementRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsInstallationRoute: DocsInstallationRoute,
  DocsQuickStartRoute: DocsQuickStartRoute,
  DocsIndexRoute: DocsIndexRoute,
  DocsConceptsPidfTermsRoute: DocsConceptsPidfTermsRoute,
  DocsConceptsScoringRoute: DocsConceptsScoringRoute,
  DocsConceptsTuningModesRoute: DocsConceptsTuningModesRoute,
  DocsVelocityConfigRoute: DocsVelocityConfigRoute,
  DocsVelocityDisruptionRoute: DocsVelocityDisruptionRoute,
  DocsVelocityFSweepRoute: DocsVelocityFSweepRoute,
  DocsVelocityKuSearchRoute: DocsVelocityKuSearchRoute,
  DocsVelocityOverviewRoute: DocsVelocityOverviewRoute,
  DocsVelocityRefinementRoute: DocsVelocityRefinementRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRoute: DocsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
